version: '3'

services:
    log-elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0 
        environment:
            - "discovery.type=single-node"
            - node.name=es01
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - "9200:9200" 
            - "9300:9300"
        volumes:
            - ../data:/usr/share/elasticsearch/data

    log-logstash:
        image: docker.elastic.co/logstash/logstash:7.8.0

    # kibana:
    #     image: kibana:7.8.0
    #     container_name: kibana
    #     environment:
    #         #- server.host=...
    #         - "server.name=central=logging"
    #         #- "elasticsearch.url=<host>:<port>"

    #     ports: 
    #         - "5601:5601"
    #     depends_on:
    #         - log-elasticsearch